provide support for having anon-cmd to anonymize subject ids

diff --git a/bin/reproin b/bin/reproin
--- a/bin/reproin
+++ b/bin/reproin
@@ -134,6 +134,10 @@ study-show|study-convert)
 		echo "Will use study specific heuristic"
 		heuristic=".heudiconv/heuristic.py"
 	fi
+	if [ -e "$heudiconvdir/anon-cmd" ]; then
+		echo "Will use study specific anon-cmd"
+		heudiconvcmd="$heudiconvcmd --anon-cmd '$heudiconvdir/anon-cmd'"
+	fi
 
 	# TODO: use datalad run/containers-run
 	grep -h -B1 "$ostudy[\"']" $listdir/*xx.txt  \
@@ -147,6 +151,7 @@ study-show|study-convert)
 		sub=$(echo "$subses" | sed -e "s,.*subject=',,g" -e "s,'),,g")
 		ses=$(echo "$subses" | sed -e "s,.*session='*,,g" -e "s/'*, .*//g" -e "s,None,,g")
 		subses_id="sub=$sub:ses=$ses"
+
 		if grep -q -R $td "$skipfile" 2>/dev/null; then
 			echo "$td skip  # $subses"
 			continue
@@ -160,11 +165,26 @@ study-show|study-convert)
 			echo "ERROR: Empty subject for $d"
 			exit 1
 		fi
-		if [ -n "$targetsub" ] && [ "$sub" != "$targetsub" ]; then
-			echo "Skipping subject $sub since != $targetsub"
+		if [ -n "$targetsub" ] && [ "${sub_orig}" != "$targetsub" ]; then
+			echo "Skipping $subses since ${sub_orig} != $targetsub"
 			continue
 		fi
-		#echo "Subject: $sub  Session: $ses"
+
+		# We must take anonymized $sub if there is anon-cmd!!!
+		sub_orig="$sub"
+		if [ -e "$heudiconvdir/anon-cmd" ]; then
+			sub_=$("$heudiconvdir/anon-cmd" "$sub" || echo "FAILED")
+			if [ $sub_ = "FAILED" ]; then
+				echo "ERROR: failed to get anonymized ID for $sub, skipping"
+				continue
+			fi
+			sub="$sub_"
+		fi
+		# Overload subses with a bit neater version reflecting possible anonymization
+		subses="$sub "
+		if [ "$sub_orig" != "$sub" ]; then subses+="($sub_orig) "; fi
+		subses+="session=$ses"
+
 		subsesheudiconvdir=$heudiconvdir/$sub
 		if [ ! -z "$ses" ]; then
 			subsesheudiconvdir+=/ses-$ses
@@ -181,10 +201,10 @@ study-show|study-convert)
 		cmd="$heudiconvcmd -f $heuristic -l $study --files $td"
 		case "$action" in
 		study-show)
-			echo "$cmd # subject=$sub session=$ses"
+			echo "$cmd # $subses"
 			;;
 		study-convert)
-			echo "Converting subject $sub for session $ses ($studydir)"
+			echo "Converting $subses ($studydir)"
 			mkdir -p "$subsesheudiconvdir"
 			logfile="$subsesheudiconvdir/heudiconv.log"
 			if ! eval "$cmd" > "$logfile" 2>&1; then
@@ -199,7 +219,7 @@ study-show|study-convert)
 			if [ -e "$vallog" ]; then
                            cp --reflink=auto "$vallog" "$subsesheudiconvdir/bids-validator.log"
 			fi
-			datalad save -m "Converted subject $sub session $ses" -r . .heudiconv .heudiconv/*
+			datalad save -m "converted subject $sub session $ses" -r . .heudiconv .heudiconv/*
 			;;
 		esac
 	done
