Prototype of lists-check command found uncommitted - to find issues problems etc

diff --git a/bin/reproin b/bin/reproin
--- a/bin/reproin
+++ b/bin/reproin
@@ -21,6 +21,11 @@ function error() {
 	echo "# ERROR: $@"
 }
 
+function debug() {
+	# echo "# DEBUG: $@"
+	:
+}
+
 
 #
 # A Master run script for a study
@@ -66,6 +71,90 @@ lists-update)
 	# studies dumped into the same folder.  Complain then!
         eval "$heudiconvcmd -f $heuristic --command ls --files $dicomdir/$Y/$M/$D/*/00*cout*" >| "$listfile"
 	exit 0
+	;;
+lists-check)
+	# TODO: add an option to just update when discrepnancy found
+	doit=1
+	Y=${2:-20??}; 
+	M=${3:-??}; 
+	declare -A todo
+	declare -A groups
+	for d in $dicomdir/$Y/$M; do
+		#D=$(basename $d)
+		M=$(basename $d)
+		Y=$(dirname $d | xargs basename)
+		if [ $Y = 2016 ]; then
+			# skip that early one
+			continue
+		fi
+		listfile="$listdir/$Y${M}xx.txt"
+		if [ ! -e $listfile ]; then
+			echo "I: no $listfile"
+			if /bin/ls -d $dicomdir/$Y/$M/*/*/00*cout*; then
+				echo "E: there were legitimatish accession folders with scouts!"
+				todo["${M}_$Y"]="scouts"
+			fi
+			continue
+		fi
+		missing=
+		for a in $dicomdir/$Y/$M/*/*; do
+			# echo "$a"
+			case "$a" in
+			*_backup)
+				if [ -e "${a%_backup}" ] ; then
+					echo "skip odd backup $a for which original also exists";
+					continue
+				fi
+				;;
+			esac
+			# ATM we react only to ones having /00*cout*
+			scouts=$(/bin/ls -1 $a/00*cout* 2>&1 | head -n 1)
+			if echo "$scouts" | grep -q "No such file or directory"; then
+				debug "no scouts under $a"
+				# ls -l $a
+				continue
+			fi
+			if ! grep -q "^$a" "$listfile"; then
+				debug "scouts: >$scouts<"
+				if echo "$scouts" | grep -qi 'permission'; then
+					# no need to try to update list if we have permissions issue
+					# ATM
+					reason="permissions? $(ls -dl $a)"
+					groups[$(stat -c '%G' "$a")]+="$a "
+				else
+					reason="unknown"
+					missing+="$a"
+				fi
+				echo "$a is missing: $reason"
+			fi
+		done
+		if [ -n "$missing" ]; then
+			todo["${M}_$Y"]="missing"
+		fi
+	done
+	exit_code=0
+	if [[ -n "${todo[@]}" ]]; then
+		echo "List of TODOs:"
+		for MY in "${!todo[@]}"; do
+			Y=${MY#*_}
+			M=${MY%_*}
+			cmd="'$0' lists-update $Y $M"
+			if [ -n "$doit" ]; then
+				$cmd
+			else
+				echo $cmd
+			fi
+		done
+		((exit_code += 1))
+	fi
+	if [[ -n "${groups[@]}" ]]; then
+		echo "List of groups for which permissions fail: ${!groups[@]}"
+		for g in "${!groups[@]}"; do
+			echo "  $g: ${groups[$g]}"
+		done
+		((exit_code += 2))
+	fi
+	exit $exit_code
 	;;
 lists-update-summary)
 	# to be used on the stderr output from heudiconv --command ls or lists-update ran by cron job
